# Generated by Django 2.2.19 on 2022-11-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='cur_capacity',
            new_name='cur_load',
        ),
    ]
